// src/main/main.cpp — beetle-adventure-racing-recomp boot host
//
// Static-recompilation PC port of Beetle Adventure Racing (N64, USA).
// Adapted from Zelda64Recomp/Zelda64Recomp @ dev (src/main/main.cpp), but written against
// THIS repo's pinned runtime (lib/N64ModernRuntime @ main, ae1ffbb), whose recomp::start()
// takes a single recomp::Configuration struct. Every type/field below was verified against
// lib/N64ModernRuntime/{librecomp,ultramodern}/include headers.
//
// Status (2026-06-28 night): boots deep. RT64 (D3D12) initializes, the SDL window opens, the ROM
// is recognized, libultra inits, and the uv module overlay bridge (src/main/overlay_bridge.cpp)
// registers relocatable modules as they load so recompiled module code runs. It currently crashes
// on module data-section relocation (a module data/.bss ref reads a garbage address). See
// docs/STATUS.md ("Next step: module data-section relocation").

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <vector>
#include <memory>
#include <filesystem>
#include <thread>
#include <chrono>
#include <atomic>

#include "ultramodern/ultramodern.hpp"        // gfx_callbacks_t, audio_callbacks_t
#include "ultramodern/renderer_context.hpp"   // renderer::callbacks_t, RendererContext, WindowHandle
#include "ultramodern/error_handling.hpp"     // error_handling::callbacks_t
#include "ultramodern/events.hpp"             // events::callbacks_t (optional)
#include "ultramodern/input.hpp"              // input::callbacks_t
#include "ultramodern/threads.hpp"            // threads::callbacks_t

#include "librecomp/game.hpp"                 // recomp::{GameEntry,SaveType,Configuration,start,...}; pulls recomp.h
#include "librecomp/rsp.hpp"                  // recomp::rsp::callbacks_t, RspUcodeFunc, OSTask
#include "librecomp/overlays.hpp"             // overlay table (registration lives in register_overlays.cpp)

#include "game/config.hpp"                    // bar::config — settings persistence + high-FPS enable
#include "game/input_config.hpp"              // bar::input_config — 4-port controller settings (input.json)
#include "main/bar_cheats.h"                  // bar_cheats — BAR cheat toggles (host-side RDRAM pokes)
#include "main/bar_input.hpp"                 // bar::input — live 4-port runtime input path
#ifdef BEETLE_ENABLE_FRONTEND
#include "frontend/bar_frontend.h"            // bar::frontend — RecompFrontend launcher/menus + input
#endif

// NOTE: BEETLE_ENABLE_UI guarded the bespoke RmlUi launcher that 019305c removed, and nothing
// defines it any more -- RecompFrontend is the only frontend and its option is
// BEETLE_ENABLE_FRONTEND. The blocks still written against it below are dead code referring to the
// deleted src/ui. They are left in place rather than removed here, because deleting them is a
// separate cleanup; but be aware that NONE of them compile into either build.

// The most-recently selected ROM path, handed to bar_ui for its (non-boot) "Play" request. The game
// itself boots from the ROM cached in the config dir (see main()'s ROM-source block), not from here.
// Set in main() before recomp::start() so the create_window callback can hand it to bar_ui.
static std::filesystem::path g_default_rom_path;

#define SDL_MAIN_HANDLED                      // we provide our own main()/entry; don't let SDL hijack it
#include <SDL.h>
#ifdef _WIN32
#include <SDL_syswm.h>                        // SDL_GetWindowWMInfo -> native HWND. Windows only: on Linux the
                                             //   WindowHandle is the SDL_Window* itself (see renderer_context.hpp),
                                             //   and this header would drag in <X11/X.h>, whose `None` macro
                                             //   collides with our enum values (SaveType::None, Pak::None, ...).
#include <timeapi.h>                          // timeBeginPeriod (1ms timer resolution); links winmm
#endif

// ----------------------------------------------------------------------------------------
// Generated by N64Recomp into RecompiledFuncs/ (externs only here).
// TODO(BAR): these exist only after `./N64Recomp beetle-adventure-racing-recomp.toml` runs on the recomp ELF.
// ----------------------------------------------------------------------------------------
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);
gpr get_entrypoint_address();   // generated; expected to resolve to BAR's entry VRAM 0x80000400

// Wires the N64Recomp-generated section/overlay tables (recomp_overlays.inl) into librecomp.
// Defined in src/main/register_overlays.cpp.
void bar_register_overlays();

// RSP microcode entry points are generated by RSPRecomp. TODO(BAR): generate BAR's stock audio
// ucode (aspMain) with RSPRecomp and return it for M_AUDTASK. Graphics ucode (F3DEX2) is handled
// by RT64 (HLE), not recompiled here. Until the audio ucode exists, audio tasks are unhandled
// (the game may exit on the first one) — acceptable for the initial build/bring-up.
// No-op RSP ucode: BAR's audio ucode (aspMain) isn't generated by RSPRecomp yet. Reporting a normal
// RSP break makes run_task() treat the task as completed (silent) instead of fatally exiting the task
// thread. Graphics tasks (M_GFXTASK) never reach here — they go to the gfx thread's send_dl path.
static RspExitReason bar_rsp_ucode_stub(uint8_t* /*rdram*/, uint32_t /*ucode_addr*/) {
    return RspExitReason::Broke;
}

// BAR's stock audio microcode (aspMain), recompiled by RSPRecomp into rsp/aspMain.cpp. Generates the
// PCM for M_AUDTASK. ON by default; set BAR_NO_AUDIO to fall back to the silent stub (escape hatch in case
// the ucode hits an unhandled indirect-jump target on some task — BAR is libultra 2.0I vs reference 2.0J/L).
// Graphics ucode (F3DEX2) goes to RT64 (HLE), not here.
RspExitReason aspMain(uint8_t* rdram, uint32_t ucode_addr);

// BAR's aspMain (recompiled from libultra 2.0I) hits an unhandled indirect-jump target on certain audio
// tasks — notably Beetle Battle — returning e.g. RspExitReason::UnhandledJumpTarget. run_task() treats any
// non-Broke exit as fatal and quick_exit()s the whole process (task_thread_func, events.cpp). Wrap aspMain
// so a single bad audio task degrades to silence for that task instead of taking the game down; normal
// tasks still run aspMain exactly as before. BAR_NO_AUDIO remains the coarse "disable all audio" escape.
static RspExitReason bar_aspMain_guarded(uint8_t* rdram, uint32_t ucode_addr) {
    RspExitReason reason = aspMain(rdram, ucode_addr);
    if (reason != RspExitReason::Broke) {
        static uint32_t warned = 0;
        if (warned++ < 8) {
            std::fprintf(stderr, "[beetle-adventure-racing-recomp] aspMain exited abnormally (reason %d) on an audio task; "
                         "skipping this task's audio instead of exiting the game\n", static_cast<int>(reason));
        }
        return RspExitReason::Broke;   // report a clean break so run_task() completes the task
    }
    return reason;
}

static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    switch (task->t.type) {
        case M_AUDTASK: {
            static const bool audio_off = std::getenv("BAR_NO_AUDIO") != nullptr;
            return audio_off ? bar_rsp_ucode_stub : bar_aspMain_guarded;
        }
        default: {
            static bool warned = false;
            if (!warned) {
                std::fprintf(stderr, "[beetle-adventure-racing-recomp] RSP task type %u -> no-op stub\n",
                             (unsigned)task->t.type);
                warned = true;
            }
            return bar_rsp_ucode_stub;
        }
    }
}

// ----------------------------------------------------------------------------------------
// Project metadata / game registration
// ----------------------------------------------------------------------------------------
static const std::string version_string = "0.1.0";   // TODO(BAR): real version string

// TODO(BAR): rom_hash is XXH3_64bits() of the byteswapped *z64* ROM — NOT the sha1.
//   Known USA sha1 = e5ab4d226c08d22f68a2edcc48870203e67454b8. Compute the XXH3-64 of the
//   validated z64 and paste it here (easiest: log XXH3_64bits() once during bring-up).
static constexpr uint64_t BAR_USA_ROM_XXH3 = 0x56cfec69d7951f9fULL;   // XXH3_64 of the USA z64 (sha1 e5ab4d22…)

// NOT static: recompui's launcher declares `extern std::vector<recomp::GameEntry> supported_games;`
// (recompui/src/base/ui_launcher.cpp) and links against the consuming project's definition — another
// of RecompFrontend's implicit project contracts, alongside patches/ui_funcs.h. It reads this table
// to decide what the launcher can offer and whether a valid ROM is present.
std::vector<recomp::GameEntry> supported_games = {
    recomp::GameEntry{
        .rom_hash              = BAR_USA_ROM_XXH3,            // TODO(BAR)
        .internal_name         = "Beetle Adventure Rac",      // exact 20 bytes at ROM offset 0x20
        // Required since the upstream runtime merge: register_game() hard-exits with "Game display
        // name was not set." if this is empty. It is also what recompui shows in the launcher.
        .display_name          = "Beetle Adventure Racing!",
        .game_id               = u8"bar.n64.us",             // stable id (arbitrary but fixed)
        .mod_game_id           = "bar",
        .save_type             = recomp::SaveType::None,      // BAR uses the Controller Pak (mempak), which
                                                             //   librecomp handles separately from SaveType.
        .is_enabled            = true,
        .decompression_routine = nullptr,                    // BAR code isn't compressed in the recomp output
        .has_compressed_code   = false,                      // TODO(BAR): verify vs your N64Recomp config
        .entrypoint_address    = get_entrypoint_address(),   // expected 0x80000400
        .entrypoint            = recomp_entrypoint,
    },
};

static std::string get_game_thread_name(const OSThread* t) {
    return "Game " + std::to_string(t->id);
}

// ----------------------------------------------------------------------------------------
// Port callback stubs. Signatures match the vendored headers; BODIES are TODO.
// ----------------------------------------------------------------------------------------

// RT64 renderer context (MANDATORY). Implemented in src/main/rt64_render_context.cpp.
std::unique_ptr<ultramodern::renderer::RendererContext>
bar_create_rt64_render_context(uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode);

// Signals from rt64_render_context.cpp that gate the deferred start_game() below.
extern std::atomic<bool> g_bar_renderer_ready;   // RT64 finished setup
extern std::atomic<bool> g_bar_vi_ticked;        // renderer presented a frame (VI thread seeded a mode)

// SDL window / gfx (gfx_callbacks_t). RT64 attaches to this window (its native HWND on Windows).
// recompui (recompui/src/base/ui_state.cpp) declares `extern SDL_Window* window;` and links against
// the consuming project's definition, so the window handle must be a non-static global with exactly
// that name. g_window stays as a reference alias so the existing call sites read unchanged and the
// two can never drift apart.
SDL_Window* window = nullptr;
static SDL_Window*& g_window = window;

// Defined further down (with the first-run ROM helpers): pops a player-facing dialog (SDL message box,
// works with no window) and logs the same text. Forward-declared here so the window/renderer setup paths
// can report a missing-Vulkan-driver failure to the user instead of dying silently to stderr.
static void bar_user_message(uint32_t sdl_flags, const char* msg);

// Controller state now lives in bar::input (src/main/bar_input.cpp): it owns the open SDL_GameController
// handles (still MAIN THREAD ONLY, via on_controller_added/removed below), samples every assigned pad
// once per frame (bar::input::sample_all_ports), and resolves each of the 4 N64 ports from its
// per-port device + rebindable bindings (bar::input::resolve_port). update_gfx drives the SDL side.

#ifdef BEETLE_ENABLE_UI
// Publish the current controller list to the Controls dialog's device dropdown (defined in bar_ui).
static void bar_publish_devices() {
    std::vector<bar_ui::UiGamepad> list;
    for (const auto& d : bar::input::enumerate_devices()) {
        list.push_back(bar_ui::UiGamepad{ d.guid, d.uid, d.display });
    }
    bar_ui::publish_gamepads(list);
}
#endif

static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    SDL_SetMainReady();
    // Windows DPI awareness. SDL_WINDOW_ALLOW_HIGHDPI alone is not enough here: unless the PROCESS is
    // marked DPI-aware before SDL_Init, Windows hands a scaled desktop to the app and lies about
    // sizes. On a 1920x1080 display at 125% that means SDL sees 1536x864, so the renderer draws at
    // physical resolution while the window is measured in logical pixels — the UI overflows the
    // window (its title clips) and, worse, mouse coordinates land about 1.25x off, so clicking a
    // menu entry activates a different one. Both hints must be set before SDL_Init to take effect.
    SDL_SetHint(SDL_HINT_WINDOWS_DPI_AWARENESS, "permonitorv2");
    // DPI_SCALING is deliberately OFF. With it on, SDL reports window geometry and mouse positions
    // in DPI-scaled logical units while the drawable — and therefore everything RT64 and recompui
    // lay out — stays in physical pixels. At 125% that is a 1.25x disagreement between where the UI
    // draws a button and where a click is reported, which shows up as having to click well away
    // from a menu entry to hit it. Awareness alone keeps both sides in physical pixels.
    SDL_SetHint(SDL_HINT_WINDOWS_DPI_SCALING, "0");
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS | SDL_INIT_GAMECONTROLLER | SDL_INIT_AUDIO) != 0) {
        std::fprintf(stderr, "[beetle-adventure-racing-recomp] SDL_Init failed: %s\n", SDL_GetError());
    }
    return nullptr;   // gfx_data_t is unused; the window is tracked in g_window
}

static ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t /*data*/) {
    // Default to a 4:3 window. BAR_WINDOW_SIZE=WxH overrides it — handy for widescreen users and for
    // QA'ing the letterbox present modes (Pillarbox/Crop/Stretch), which only differ on a non-4:3 window.
    int win_w = 960, win_h = 720;
    if (const char *ws = std::getenv("BAR_WINDOW_SIZE")) {
        int w = 0, h = 0;
        if (std::sscanf(ws, "%dx%d", &w, &h) == 2 && w >= 320 && h >= 240) {
            win_w = w;
            win_h = h;
        }
    }
    // RT64's backend is per-platform: D3D12 on Windows (it binds to the raw HWND, so the SDL window needs
    // no graphics-API flag), Vulkan on Linux/Android, Metal on macOS. The Vulkan and Metal backends create
    // their swapchain surface *through SDL* (SDL_Vulkan_CreateSurface / SDL_Metal_CreateView), which requires
    // the window to have been created with the matching flag. Without it SDL fails the surface call with
    // "The specified window isn't a Vulkan window" and RT64 then dereferences the null surface and segfaults.
    // We deliberately omit the flag on Windows so RT64's default D3D12 path is unaffected.
    Uint32 window_flags = SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI;
#if defined(__APPLE__)
    window_flags |= SDL_WINDOW_METAL;
#elif !defined(_WIN32)
    window_flags |= SDL_WINDOW_VULKAN;
#endif
    g_window = SDL_CreateWindow("Beetle Adventure Racing: Recompiled",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, win_w, win_h,
        window_flags);
    if (g_window == nullptr) {
        // With SDL_WINDOW_VULKAN set, SDL tries to load the Vulkan loader here — so this branch also fires
        // when the machine has no usable Vulkan driver at all. Tell the player how to fix it rather than
        // leaving them with a silent black window / a stderr line no GUI launcher ever shows.
        std::fprintf(stderr, "[beetle-adventure-racing-recomp] SDL_CreateWindow failed: %s\n", SDL_GetError());
#if !defined(_WIN32) && !defined(__APPLE__)
        bar_user_message(SDL_MESSAGEBOX_ERROR,
            "Beetle Adventure Racing: Recompiled could not create a Vulkan window.\n\n"
            "Your system is most likely missing a Vulkan driver. Install your GPU's Vulkan support:\n"
            "  - AMD / Intel (Mesa):  sudo apt install mesa-vulkan-drivers\n"
            "  - NVIDIA:              install the proprietary NVIDIA driver package\n"
            "  - Then verify with:    vulkaninfo   (from the vulkan-tools package)\n\n"
            "The detailed SDL error was printed to the terminal.");
        // Fatal and unrecoverable: exit cleanly right here rather than returning an empty handle and letting
        // RT64 crash on a null window (or raising a second, vaguer dialog from ultramodern's setup-failure
        // path). The modal dialog above has already been dismissed by the user by this point.
        std::_Exit(EXIT_FAILURE);
#endif
        return {};
    }
#ifdef BEETLE_ENABLE_UI
    // Register the RmlUi render hooks now, before the gfx thread constructs RT64 (recomp::start
    // calls create_window on this thread *before* spawning the gfx thread that runs
    // create_render_context → app->setup, which is when RT64 fires the UI init hook).
    bar_ui::install(g_window, g_default_rom_path);
#endif

#ifdef _WIN32
    // Windows: RT64 attaches to the native HWND and needs the id of the thread that owns the window.
    // create_window runs on the same (main) thread that pumps update_gfx below, so that's this thread.
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    if (SDL_GetWindowWMInfo(g_window, &wm_info) != SDL_TRUE) {
        std::fprintf(stderr, "[beetle-adventure-racing-recomp] SDL_GetWindowWMInfo failed: %s\n", SDL_GetError());
        return {};
    }
    return ultramodern::renderer::WindowHandle{ wm_info.info.win.window, GetCurrentThreadId() };
#else
    // Linux/Android: WindowHandle is the SDL_Window* itself (RT64 derives the native handle from it).
    return g_window;
#endif
}

static void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t /*data*/) {
#ifdef BEETLE_ENABLE_FRONTEND
    // recompinput owns the SDL queue and must be its ONLY poller -- a second loop would race it and
    // each would swallow events the other needed. It is pumped here rather than from input_poll
    // because this callback runs even with no game started, which is where the launcher lives.
    bar::frontend::pump_events();
#else
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
        if (event.type == SDL_QUIT) {
            ultramodern::quit();
            continue;
        }
        // Game controller hotplug. SDL queues a DEVICEADDED for controllers already present at init,
        // so this also picks up controllers plugged in before launch. bar::input tracks all of them
        // (up to 4 ports can be driven); the Controls dialog assigns which pad drives which port.
        if (event.type == SDL_CONTROLLERDEVICEADDED) {
            bar::input::on_controller_added(event.cdevice.which);
#ifdef BEETLE_ENABLE_UI
            bar_publish_devices();
#endif
            continue;
        }
        if (event.type == SDL_CONTROLLERDEVICEREMOVED) {
            bar::input::on_controller_removed(event.cdevice.which);
#ifdef BEETLE_ENABLE_UI
            bar_publish_devices();
#endif
            continue;
        }
#ifdef BEETLE_ENABLE_UI
        // While the Controls dialog is waiting for a key/button to (re)assign a binding, DON'T consume
        // Esc/F1, the Back button, or synthesize menu-nav — forward the raw event so it can be captured
        // as the binding (Esc cancels the capture inside bar_ui). Skip these three intercepts entirely.
        const bool rebinding = bar_ui::rebind_listening();
        // Esc / F1 toggle the in-game pause menu (pauses the simulation; no effect pre-game — the
        // launcher is already up). The game never reads these keys (game input is GetAsyncKeyState /
        // controller based), so we consume them here.
        if (!rebinding && event.type == SDL_KEYDOWN && event.key.repeat == 0 &&
            (event.key.keysym.sym == SDLK_ESCAPE || event.key.keysym.sym == SDLK_F1)) {
            bar_ui::toggle_pause_menu();
            continue;
        }
        // Controller Back/View/Select button also toggles the pause menu (N64 pads have no such
        // button, so it never conflicts with game input).
        if (!rebinding && event.type == SDL_CONTROLLERBUTTONDOWN && event.cbutton.button == SDL_CONTROLLER_BUTTON_BACK) {
            bar_ui::toggle_pause_menu();
            continue;
        }
        // Controller navigation of the menu: translate buttons to the keyboard nav the menu already
        // handles (D-pad -> arrows = move focus; A -> Enter = activate). Synthesize a key event and feed
        // it through the same path. Only while the menu owns input (and not while capturing a rebind).
        if (!rebinding && bar_ui::menu_capturing_input() && event.type == SDL_CONTROLLERBUTTONDOWN) {
            SDL_Keycode key = 0;
            switch (event.cbutton.button) {
                case SDL_CONTROLLER_BUTTON_DPAD_UP:    key = SDLK_UP;     break;
                case SDL_CONTROLLER_BUTTON_DPAD_DOWN:  key = SDLK_DOWN;   break;
                case SDL_CONTROLLER_BUTTON_DPAD_LEFT:  key = SDLK_LEFT;   break;
                case SDL_CONTROLLER_BUTTON_DPAD_RIGHT: key = SDLK_RIGHT;  break;
                case SDL_CONTROLLER_BUTTON_A:          key = SDLK_RETURN; break;
                default: break;
            }
            if (key != 0) {
                SDL_Event k{};
                k.type = SDL_KEYDOWN;
                k.key.type = SDL_KEYDOWN;
                k.key.state = SDL_PRESSED;
                k.key.repeat = 0;
                k.key.keysym.sym = key;
                k.key.keysym.scancode = SDL_GetScancodeFromKey(key);
                bar_ui::handle_sdl_event(k);
            }
            continue;
        }
        // While the launcher/settings/cheats menu owns input, forward events to RmlUi (drained on
        // the render thread). Once the game starts, the menu hides and input goes to the game.
        if (bar_ui::menu_capturing_input()) {
            bar_ui::handle_sdl_event(event);
        }
#endif
    }
#endif // BEETLE_ENABLE_FRONTEND

    // Shared by BOTH builds: the game's own per-frame input work. The frontend replaces the event
    // PUMP, not the N64-port input path -- and mempak_flush_all in particular must keep running, or
    // Controller Pak saves would never reach disk.
    bar::input::sample_all_ports();   // refresh every assigned pad's snapshot on this (main) thread
    bar::input::flush_rumble();       // issue SDL rumble for any port that wants it (main thread)
    bar::input::mempak_flush_all();   // persist any Controller Pak writes (cheap no-op when clean)
}

// Audio (audio_callbacks_t) — SDL2 queued-audio backend.
// The libultra->ultramodern AI chain (librecomp/src/ai.cpp -> ultramodern/src/audio.cpp) delivers the
// game's PCM here as `count` interleaved-stereo int16 samples pointing straight into RDRAM (no swap done
// upstream). EMPIRICALLY VERIFIED (captured BAR menu music, offline autocorrelation): the raw int16
// values are ALREADY correct host-order (librecomp's RDRAM word-swizzle yields correct s16 on raw read);
// byteswapping them produces white-noise "screeching". The word-swizzle delivers the pair as [R,L], so
// we channel-swap to [L,R] (matches Zelda64Recompiled's backend). BAR_AUDIO_XFORM overrides:
//   0 = as-is, 1 = byteswap only, 2 = channel-swap only [default, correct], 3 = byteswap + channel-swap.
//
// SAFETY: the output device is opened (and sound produced) ONLY when BAR_AUDIO_PLAY is set. By default —
// and while verifying correctness — NO device is opened and NOTHING plays. BAR_AUDIO_CAPTURE=<path> dumps
// the raw (untransformed) received stream so the correct transform can be checked offline without audio.
static SDL_AudioDeviceID g_audio_dev = 0;
static uint32_t g_dev_freq  = 0;        // freq the SDL device is currently open at
static uint32_t g_game_freq = 0;        // last freq the game requested (for capture/WAV)
static constexpr int kBarBytesPerFrame = 2 * (int)sizeof(int16_t);   // stereo s16
static std::FILE* g_audio_capture = nullptr;
static size_t g_audio_capture_bytes = 0;

static bool bar_audio_play_enabled() {
    // Audio output ON by default; BAR_NO_AUDIO disables the device (and the ucode, see get_rsp_microcode).
    static const bool on = std::getenv("BAR_NO_AUDIO") == nullptr;
    return on;
}
static int bar_audio_xform() {
    static const int x = []{ const char* e = std::getenv("BAR_AUDIO_XFORM"); return e ? std::atoi(e) : 2; }();
    return x;
}

static void bar_open_audio(uint32_t freq) {
    if (freq == 0) return;
    g_game_freq = freq;
    if (g_audio_capture == nullptr) {
        static bool tried = false;
        if (!tried) { tried = true;
            const char* cap = std::getenv("BAR_AUDIO_CAPTURE");
            if (cap && *cap) { g_audio_capture = std::fopen(cap, "wb");
                std::fprintf(stderr, "[beetle-adventure-racing-recomp] audio capture -> %s\n", cap); }
        }
    }
    if (!bar_audio_play_enabled()) return;          // muted: never open a device, never play
    if (g_audio_dev != 0 && g_dev_freq == freq) return;
    if (g_audio_dev != 0) { SDL_CloseAudioDevice(g_audio_dev); g_audio_dev = 0; }
    if (SDL_WasInit(SDL_INIT_AUDIO) == 0 && SDL_InitSubSystem(SDL_INIT_AUDIO) != 0) {
        std::fprintf(stderr, "[beetle-adventure-racing-recomp] SDL_InitSubSystem(AUDIO) failed: %s\n", SDL_GetError());
        return;
    }
    SDL_AudioSpec want{}, have{};
    want.freq = (int)freq; want.format = AUDIO_S16SYS; want.channels = 2; want.samples = 1024; want.callback = nullptr;
    g_audio_dev = SDL_OpenAudioDevice(nullptr, 0, &want, &have, 0);
    if (g_audio_dev == 0) {
        std::fprintf(stderr, "[beetle-adventure-racing-recomp] SDL_OpenAudioDevice failed: %s\n", SDL_GetError());
        return;
    }
    g_dev_freq = (uint32_t)have.freq;
    SDL_PauseAudioDevice(g_audio_dev, 0);
}

static void queue_samples(int16_t* samples, size_t count) {
    if (samples == nullptr || count == 0) return;
    // Capture the RAW received stream (no transform) for offline analysis, capped at ~16 MB.
    if (g_audio_capture && g_audio_capture_bytes < (16u << 20)) {
        size_t n = std::fwrite(samples, sizeof(int16_t), count, g_audio_capture);
        g_audio_capture_bytes += n * sizeof(int16_t);
    }
    if (g_audio_dev == 0) return;                    // muted (default) — produce no sound
    const int xf = bar_audio_xform();
    const bool byteswap = (xf == 1 || xf == 3);
    const bool chanswap = (xf == 2 || xf == 3);
    static std::vector<int16_t> out;
    out.resize(count);
    for (size_t i = 0; i < count; i++) {
        uint16_t v = (uint16_t)samples[i];
        out[i] = byteswap ? (int16_t)(uint16_t)((v >> 8) | (v << 8)) : (int16_t)v;
    }
    if (chanswap) { for (size_t i = 0; i + 1 < count; i += 2) { int16_t t = out[i]; out[i] = out[i+1]; out[i+1] = t; } }
    { static const bool dbg = std::getenv("BAR_AUDIO_DBG") != nullptr; if (dbg) {
        extern int g_bar_audio_peak; extern long g_bar_audio_clip;
        for (size_t i = 0; i < count; i++) { int a = out[i] < 0 ? -(int)out[i] : out[i];
            if (a > g_bar_audio_peak) g_bar_audio_peak = a; if (a >= 32760) g_bar_audio_clip++; } } }
    SDL_QueueAudio(g_audio_dev, out.data(), (Uint32)(count * sizeof(int16_t)));
}

int  g_bar_audio_peak = 0;   // diag (BAR_AUDIO_DBG): peak |sample| + saturation count
long g_bar_audio_clip = 0;

static size_t get_frames_remaining() {
    if (g_audio_dev == 0) return 0;
    size_t frames = (size_t)(SDL_GetQueuedAudioSize(g_audio_dev) / (Uint32)kBarBytesPerFrame);
    { static const bool dbg = std::getenv("BAR_AUDIO_DBG") != nullptr; if (dbg) {
        // Inter-call wall delta (called ~once per game frame). Flag genuine near-underruns (queue almost
        // empty) and egregious single-frame stalls (>50 ms = >3 VI) — not normal 16.6 ms frames.
        static auto last = std::chrono::steady_clock::now(); auto now = std::chrono::steady_clock::now();
        double dms = std::chrono::duration<double, std::milli>(now - last).count(); last = now;
        if ((frames < 150 && frames > 0) || dms > 50.0) { std::fprintf(stderr, "[beetle-adventure-racing-recomp] audio LOW: queued=%zu frameDelta=%.1fms\n", frames, dms); std::fflush(stderr); }
        static size_t minq = (size_t)-1, maxq = 0; static int n = 0;
        if (frames < minq) minq = frames; if (frames > maxq) maxq = frames;
        if ((++n % 60) == 0) {
            std::fprintf(stderr, "[beetle-adventure-racing-recomp] audio: queued now=%zu min=%zu max=%zu | peak=%d clipped=%ld%s\n",
                         frames, minq, maxq, g_bar_audio_peak, g_bar_audio_clip,
                         (minq == 0) ? "  <<< UNDERRUN" : "");
            std::fflush(stderr); minq = (size_t)-1; maxq = 0; g_bar_audio_peak = 0; g_bar_audio_clip = 0;
        } } }
    return frames;
}

static void set_frequency(uint32_t freq) {
    if (freq != 0 && freq != g_dev_freq) bar_open_audio(freq);
}

// Input (input::callbacks_t). Each of the 4 N64 ports is reported connected per the live InputConfig
// (bar::input); its buttons/stick come from bar_poll_keyboard -> bar::input::resolve_port, resolving
// the port's assigned device (keyboard or a specific SDL pad) through its rebindable bindings. The
// Controls dialog (src/ui) edits that config.
static void input_poll() {
    // Deliberately empty. wave-race-64-recomp pumps recompinput from here, but ultramodern does not
    // call this callback until a game is running — and this port sits at the launcher with no game
    // started, because recompui's "Start Game" owns that. Pumping only from here left nothing
    // draining SDL's queue at the launcher, so the window stopped answering Windows and went
    // "Not Responding". The pump therefore lives in update_gfx, which does run pre-game.
}

// bar_poll_keyboard (defined below) is the single input source — BAR_AUTOPLAY script or live
// keyboard. It feeds BOTH the high-level path (this callback, for ultramodern's osContGetReadData)
// and the low-level SI path (os_unimpl_stubs.cpp's __osSiRawStartDma fill), so input reaches the
// game whichever way it polls.
extern "C" uint16_t bar_poll_keyboard(int port, int8_t* stick_x, int8_t* stick_y);

static bool input_get(int controller_num, uint16_t* buttons, float* x, float* y) {
    if (!bar::input::port_connected(controller_num)) {
        return false;   // this N64 port has no controller / device assigned
    }
    int8_t sx = 0, sy = 0;
    const uint16_t b = bar_poll_keyboard(controller_num, &sx, &sy);
    if (buttons != nullptr) *buttons = b;
    if (x != nullptr)       *x = (float)sx / 80.0f;   // N64 stick range -> ~[-1, 1]
    if (y != nullptr)       *y = (float)sy / 80.0f;
    return true;
}

static void input_set_rumble(int controller_num, bool rumble) {
    bar::input::set_rumble(controller_num, rumble);
}

static ultramodern::input::connected_device_info_t input_get_device_info(int controller_num) {
    using namespace ultramodern::input;
    if (!bar::input::port_connected(controller_num)) {
        return connected_device_info_t{ Device::None, Pak::None };
    }
    // A Rumble Pak is surfaced to the high-level path so ultramodern's osMotorInit succeeds; a
    // Controller Pak is emulated at the SI/joybus level (status bit + mempak), so it reports no
    // high-level pak here (we don't want the runtime treating it as a rumble device).
    // Report the configured accessory. Controller Pak support needs BOTH halves and neither works
    // alone (verified by reverting each):
    //   1. here — ultramodern sets OSContStatus.status = (connected_pak != Pak::None), and BAR gates
    //      its whole pak path on that status. With None it never even issues an SI pak query.
    //   2. os_unimpl_stubs.cpp — answers the SHORT-format status query and serves READ_PAK/WRITE_PAK
    //      against the 32 KiB per-port store, which is where the notes actually live.
    //
    // Pak::ControllerPak was added to the ultramodern fork for this: it reports the accessory as
    // present without osMotorInit accepting the port as a rumble device (it only accepts RumblePak).
    Pak pak = Pak::None;
    switch (bar::input::port_pak(controller_num)) {
        case bar::input_config::PakType::ControllerPak: pak = Pak::ControllerPak; break;
        case bar::input_config::PakType::RumblePak:     pak = Pak::RumblePak;     break;
        case bar::input_config::PakType::None:          pak = Pak::None;          break;
    }
    return connected_device_info_t{ Device::Controller, pak };
}

// Keyboard -> N64 controller (port 0). BAR reads the pad via the raw SI/PIF path, so
// __osSiRawStartDma_recomp (os_unimpl_stubs.cpp) calls this to fill the read buffer. Uses Win32 async
// key state, gated to when the game window is focused. Bindings (port 0):
//   Analog stick: Arrows   A: X   B: Z   Start: Enter   Z-trigger: Shift   L: Q   R: W   C-buttons: I/J/K/L   D-pad: T/F/G/H
// Scripted auto-input for headless menu/race testing. Set BAR_AUTOPLAY to a space-separated
// sequence of "frames:hexbuttons" phases, played in order then held neutral. Hex is the N64 button
// mask (START=1000 A=8000 B=4000 Z=2000; d-pad U=0800 D=0400 L=0200 R=0100). D-pad bits also drive
// the analog stick so menus reading either respond. Bypasses the focus gate.
// Example: BAR_AUTOPLAY="180:0 12:1000 60:0 12:8000"  -> wait, tap START, wait, tap A.
static uint16_t bar_autoplay_poll(const char* script, int8_t* stick_x, int8_t* stick_y) {
    struct Phase { int dur; uint16_t btn; };
    static std::vector<Phase> phases;
    static bool parsed = false;
    static size_t idx = 0;
    static int held = 0;
    static unsigned long long fc = 0;
    if (!parsed) {
        parsed = true;
        for (const char* p = script; *p; ) {
            while (*p == ' ' || *p == '\t') ++p;
            if (!*p) break;
            char* e = nullptr;
            long dur = std::strtol(p, &e, 10);
            uint16_t btn = 0;
            if (e && *e == ':') btn = (uint16_t)std::strtol(e + 1, &e, 16);
            p = (e && e != p) ? e : p + 1;
            if (dur > 0) phases.push_back({(int)dur, btn});
        }
        std::fprintf(stderr, "[beetle-adventure-racing-recomp] AUTOPLAY: %zu phases parsed\n", phases.size());
        std::fflush(stderr);
    }
    ++fc;
    uint16_t btn = 0;
    if (idx < phases.size()) {
        btn = phases[idx].btn;
        if (++held >= phases[idx].dur) {
            held = 0; ++idx;
            std::fprintf(stderr, "[beetle-adventure-racing-recomp] AUTOPLAY -> phase %zu/%zu @fc=%llu next=0x%04X\n",
                         idx, phases.size(), fc, (unsigned)(idx < phases.size() ? phases[idx].btn : 0));
            std::fflush(stderr);
        }
    }
    int sx = 0, sy = 0;
    if (btn & 0x0800) sy += 80;
    if (btn & 0x0400) sy -= 80;
    if (btn & 0x0200) sx -= 80;
    if (btn & 0x0100) sx += 80;
    if (stick_x) *stick_x = (int8_t)sx;
    if (stick_y) *stick_y = (int8_t)sy;
    return btn;
}

// BAR_SHOTS="frame:path frame:path ..." — request an internal-render screenshot (RT64 GPU readback -> PNG)
// at each listed frame, on the SAME frame counter as BAR_AUTOPLAY so captures line up with scripted input.
extern "C" void bar_rt64_request_screenshot(const char *path);
static void bar_shots_poll() {
    struct Shot { unsigned long frame; std::string path; };
    static std::vector<Shot> shots;
    static bool parsed = false;
    static size_t idx = 0;
    static unsigned long long fc = 0;
    if (!parsed) {
        parsed = true;
        if (const char *s = std::getenv("BAR_SHOTS")) {
            for (const char *p = s; *p; ) {
                while (*p == ' ' || *p == '\t') ++p;
                if (!*p) break;
                char *e = nullptr;
                long fr = std::strtol(p, &e, 10);
                if (e && *e == ':') {
                    const char *ps = e + 1, *pe = ps;
                    while (*pe && *pe != ' ' && *pe != '\t') ++pe;
                    if (fr > 0 && pe > ps) shots.push_back({ (unsigned long)fr, std::string(ps, pe - ps) });
                    p = pe;
                } else {
                    p = (e && e != p) ? e : p + 1;
                }
            }
            std::fprintf(stderr, "[beetle-adventure-racing-recomp] BAR_SHOTS: %zu scheduled\n", shots.size());
        }
    }
    ++fc;
    while (idx < shots.size() && fc >= shots[idx].frame) {
        bar_rt64_request_screenshot(shots[idx].path.c_str());
        std::fprintf(stderr, "[beetle-adventure-racing-recomp] BAR_SHOTS -> %s @fc=%llu\n", shots[idx].path.c_str(), (unsigned long long)fc);
        ++idx;
    }
}

// BAR_SHOT_BURST="fc:dir:count" — at input frame fc, tell RT64 to capture the next `count` presents to
// dir/fNNNN.png (one per present). For animations the input timeline can't sample (film-roll transition:
// the game blocks in a render loop and stops polling input, so BAR_SHOTS frames freeze mid-roll). Trigger
// a few frames BEFORE the transition, while fc is still advancing; RT64 then counts presents on its own.
extern "C" void bar_rt64_start_burst(const char *dir, int count);
static void bar_burst_poll() {
    static bool parsed = false, fired = false;
    static unsigned long fc_trigger = 0; static int count = 0; static std::string dir;
    static unsigned long long fc = 0;
    if (!parsed) {
        parsed = true;
        if (const char *s = std::getenv("BAR_SHOT_BURST")) {
            std::string spec(s);
            size_t c1 = spec.find(':'), c2 = (c1 == std::string::npos) ? std::string::npos : spec.find(':', c1 + 1);
            if (c2 != std::string::npos) {
                fc_trigger = std::strtoul(spec.substr(0, c1).c_str(), nullptr, 10);
                dir = spec.substr(c1 + 1, c2 - c1 - 1);
                count = std::atoi(spec.substr(c2 + 1).c_str());
            }
            std::fprintf(stderr, "[beetle-adventure-racing-recomp] BAR_SHOT_BURST: fc=%lu dir=%s count=%d\n", fc_trigger, dir.c_str(), count);
        }
    }
    ++fc;
    if (!fired && count > 0 && fc >= fc_trigger) {
        fired = true;
        bar_rt64_start_burst(dir.c_str(), count);
        std::fprintf(stderr, "[beetle-adventure-racing-recomp] BAR_SHOT_BURST triggered @fc=%llu\n", (unsigned long long)fc);
        std::fflush(stderr);
    }
}

// The gated per-port input entry. Both the low-level SI/PIF stub (os_unimpl_stubs.cpp) and the
// high-level input_get callback call this for each port. The per-port device + rebindable bindings
// live in bar::input (bar_input.cpp); this wrapper keeps the GLOBAL gates + port-0 test tooling:
//   * BAR_SHOTS / BAR_SHOT_BURST screenshot scheduling (once per SI poll, port 0),
//   * BAR_AUTOPLAY scripted input (headless testing, port 0),
//   * freeze while the menu owns input, and the window-focus gate.
extern "C" uint16_t bar_poll_keyboard(int port, int8_t* stick_x, int8_t* stick_y) {
    if (stick_x) *stick_x = 0;
    if (stick_y) *stick_y = 0;
    if (port < 0 || port >= 4) return 0;
    if (port == 0) {
        bar_shots_poll();
        bar_burst_poll();
        static const char* autoplay = std::getenv("BAR_AUTOPLAY");
        if (autoplay && *autoplay) return bar_autoplay_poll(autoplay, stick_x, stick_y);
    }
#ifdef BEETLE_ENABLE_UI
    // While the launcher/settings/cheats/controls overlay is open, freeze game input so menu
    // navigation (arrows/enter) doesn't also drive the car.
    if (bar_ui::menu_capturing_input()) return 0;
#endif
#ifdef BEETLE_ENABLE_FRONTEND
    // Same idea, but asked of recompui, which reports whether a context is ACTUALLY capturing input
    // rather than merely being open. That distinction matters: the legacy check froze game input for
    // as long as its overlay existed, so a normal launch reached the game with a dead keyboard.
    if (bar::frontend::menu_capturing_input()) return 0;
#endif
    // Only read the keyboard while our window actually holds input focus, so we don't drive the car
    // when the user has tabbed away. SDL tracks focus the same way on every platform.
    if (g_window != nullptr && !(SDL_GetWindowFlags(g_window) & SDL_WINDOW_INPUT_FOCUS)) return 0;
    return bar::input::resolve_port(port, stick_x, stick_y);
}

// Error handling (error_handling::callbacks_t). ultramodern calls this for FATAL startup errors — most
// importantly the renderer-setup failures in events.cpp (Vulkan loader missing / no compatible GPU), after
// which it throws to abort. Route it through a real SDL dialog (bar_user_message, forward-declared above)
// rather than only stderr, so a player who double-clicked the app actually sees why it refused to start
// instead of being left with a silent black window. bar_user_message still logs the same text to stderr.
static void message_box(const char* msg) { bar_user_message(SDL_MESSAGEBOX_ERROR, msg); }

// "Restart Game" (pause menu): the recompiled game can't be cleanly re-entered in-process, so restart
// the whole process — relaunch the exe with the same arguments, then quit this instance. Declared in
// src/ui/bar_ui.cpp. Non-static so the UI TU can link to it.
void bar_restart_game() {
#ifdef _WIN32
    char exe[MAX_PATH] = {};
    GetModuleFileNameA(nullptr, exe, MAX_PATH);
    std::string cmd = GetCommandLineA();   // relaunch with the same args (ROM path, etc.) + same cwd
    STARTUPINFOA si{}; si.cb = sizeof(si);
    PROCESS_INFORMATION pi{};
    if (CreateProcessA(exe, cmd.empty() ? nullptr : cmd.data(), nullptr, nullptr, FALSE, 0,
                       nullptr, nullptr, &si, &pi)) {
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
    } else {
        std::fprintf(stderr, "[beetle-adventure-racing-recomp] restart: CreateProcess failed (%lu)\n", (unsigned long)GetLastError());
    }
#endif
    ultramodern::quit();   // exit this instance (the fresh one takes over)
}

// ---------------------------------------------------------------------------------------------------
// First-run ROM setup helpers. These run in main() BEFORE recomp::start(), i.e. before the renderer
// and before ultramodern's message-box callback exist. Static recompilation ships no game data — the
// player supplies their own legally-dumped ROM, which librecomp validates by hash and caches in the
// config directory so it's only requested once.
// ---------------------------------------------------------------------------------------------------

// Show a player-facing dialog and log the same text. SDL_ShowSimpleMessageBox works with no window,
// unlike the stderr-only message_box() above (which nobody sees when launched from a GUI/launcher).
static void bar_user_message(uint32_t sdl_flags, const char* msg) {
    std::fprintf(stderr, "[beetle-adventure-racing-recomp] %s\n", msg);
#ifdef BEETLE_ENABLE_FRONTEND
    // The release build is /SUBSYSTEM:WINDOWS, so stderr goes nowhere a player will ever look.
    SDL_ShowSimpleMessageBox(sdl_flags, "Beetle Adventure Racing: Recompiled", msg, nullptr);
#else
    // The headless build keeps stderr only: a modal box would hang an automated run.
    (void)sdl_flags;
#endif
}

// Human-readable explanation for a ROM validation failure.
static const char* bar_rom_error_text(recomp::RomValidationError err) {
    switch (err) {
        case recomp::RomValidationError::FailedToOpen:     return "The selected file could not be opened.";
        case recomp::RomValidationError::NotARom:          return "That file doesn't look like a Nintendo 64 ROM.";
        case recomp::RomValidationError::IncorrectRom:     return "That isn't a Beetle Adventure Racing ROM.";
        case recomp::RomValidationError::IncorrectVersion: return "Wrong version - this port needs the USA release of Beetle Adventure Racing.";
        case recomp::RomValidationError::NotYet:           return "That ROM is recognized but isn't supported yet.";
        default:                                           return "The ROM could not be loaded.";
    }
}

// Validate `path` and, on success, cache it in the config dir (start_game() then loads it from there).
// On failure, explain why to the player. Returns true only when a valid ROM is now stored.
static bool bar_select_and_report(const std::filesystem::path& path, std::u8string& game_id) {
    recomp::RomValidationError err = recomp::select_rom(path, game_id);
    if (err == recomp::RomValidationError::Good) {
        g_default_rom_path = path;   // keep bar_ui's (non-boot) "Play" request in sync
        return true;
    }
    bar_user_message(SDL_MESSAGEBOX_ERROR,
        (std::string(bar_rom_error_text(err)) + "\n\n" + path.string()).c_str());
    return false;
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
#ifdef _WIN32
    { extern void bar_install_crash_handler(); bar_install_crash_handler(); }   // symbolized backtrace on AV
#endif
#ifdef _WIN32
    // Raise the Windows timer resolution to 1ms. CRITICAL for menu/sparse-workload framerate: the game's
    // VI-synced RCP scheduler + our runtime's gfx/task threads hand work off via timed waits. At the default
    // ~15.6ms timer resolution, each wake quantizes to ~15.6ms, so a single gfx round-trip costs ~2 quanta
    // (~32ms) and a menu frame several — capping the menu at ~10fps. (A race never waits — it always has gfx
    // queued — so it was unaffected and this was wrongly dismissed as "jitter only".) winmm is linked.
    if (std::getenv("BAR_NO_TIMER_FIX") == nullptr) timeBeginPeriod(1);  // R6 bisect: BAR_NO_TIMER_FIX=1 reverts this menu-FPS fix
#endif

    recomp::Version project_version{};
    if (!recomp::Version::from_string(version_string, project_version)) {
        message_box(("Invalid version string: " + version_string).c_str());
        return EXIT_FAILURE;
    }

    // Config/save directory: a real per-user folder (%LOCALAPPDATA%\beetle-adventure-racing-recomp on Windows;
    // ~/.config/beetle-adventure-racing-recomp on Linux), or the exe dir when a portable.txt is present. librecomp
    // writes saves / mod config here.
    recomp::register_config_path(bar::config::get_app_config_directory());

    // Load persisted graphics settings (or write defaults on first run) and push them into the
    // runtime. This also enables RT64 high-FPS frame interpolation: the default config sets
    // rr_option = Display, so presentation tracks the monitor refresh while the game/VI/audio
    // clock stays locked at its native 60 Hz (identical game speed — see
    // docs/SETTINGS_MENU_AND_HIGH_FPS.md). Must run before recomp::start() so the renderer reads
    // it when it constructs the RT64 context.
    bar::config::load_and_apply_graphics();

    // Load persisted controller/input settings (input.json) and push them into the live 4-port input
    // path. The Controls dialog edits the same config; ports 1-3 default to unplugged so single-player
    // behavior is unchanged. Must run before recomp::start() so the first controller poll sees it.
    //
    // FIRST-RUN DEFAULT: if a game controller is plugged in the very first time we run (no input.json
    // yet), default port 1 to that controller with the "Default Gamepad" map; otherwise keep the
    // keyboard default. We enumerate here with a minimal early SDL_Init (idempotent — create_gfx
    // re-inits the full set); the device-level GUID matches what bar_input later opens.
    {
        const bool first_run = !bar::input_config::config_file_exists();
        bar::input_config::InputConfig cfg = bar::input_config::load();   // writes keyboard default on first run
        if (first_run) {
            SDL_SetMainReady();
            SDL_Init(SDL_INIT_GAMECONTROLLER);
            std::string guid, name;
            for (int i = 0; i < SDL_NumJoysticks(); i++) {
                if (!SDL_IsGameController(i)) continue;
                char buf[33] = {};
                SDL_JoystickGetGUIDString(SDL_JoystickGetDeviceGUID(i), buf, sizeof(buf));
                const char* nm = SDL_GameControllerNameForIndex(i);
                guid = buf;
                name = (nm != nullptr && *nm != '\0') ? nm : "Controller";
                break;
            }
            if (!guid.empty()) {
                using namespace bar::input_config;
                cfg.ports[0].connected    = true;
                cfg.ports[0].device       = DeviceRef{ DeviceType::Gamepad, guid, name, {} };
                cfg.ports[0].profile_name = "Default Gamepad";
                if (const BindingProfile* pr = find_profile(cfg, "Default Gamepad")) cfg.ports[0].bindings = pr->bindings;
                set(cfg);   // persist the controller default so it sticks
                std::fprintf(stderr, "[beetle-adventure-racing-recomp] first run: defaulting port 1 to controller \"%s\"\n", name.c_str());
            }
        }
        bar::input::set_config(cfg);
    }

    // Load persisted cheat toggles (applied per-frame from the SI hook once the game runs; also
    // editable live via the in-game cheats menu — F1).
    bar_cheats::load();

    // Teach librecomp about BAR (hash / entrypoint / save type).
    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }

    // Wire the generated section/overlay tables so BAR's ~130 relocatable modules resolve at runtime.
    bar_register_overlays();
    // TODO(BAR): bar::register_patches(); once patches exist.

    // ---- ROM source ----
    // Resolution order: a ROM already validated + cached in the config dir from a previous run
    // (is_rom_valid) > an explicit path argument (dev / CLI) > a native "Open ROM" picker on first
    // run. select_rom() validates the hash and copies the ROM into the config dir; start_game() then
    // loads it back from there, so the player is only ever asked for the ROM once.
    std::u8string game_id = supported_games[0].game_id;
    recomp::check_all_stored_roms();                 // populate is_rom_valid() from the config dir
    bool have_rom = recomp::is_rom_valid(game_id);

    // An explicit path (e.g. `beetle-adventure-racing-recomp "C:\path\Beetle.z64"`) wins and is re-validated + cached.
    if (!have_rom && argc > 1) {
        have_rom = bar_select_and_report(std::filesystem::path(argv[1]), game_id);
    }

    // No ROM yet: how that is handled depends on which build this is.
    //
    // The frontend build must NOT bail out here. Its launcher already owns the decision --
    // add_start_game_or_load_rom_option() (see src/frontend/bar_frontend.cpp) shows "Load ROM" until
    // librecomp reports a valid ROM, runs the picker, and calls start_game() itself. Exiting here
    // would run before the launcher ever appeared, so a fresh install could never reach it: the whole
    // first-run experience of a released build was a message box saying to pass a path on the command
    // line. This block used to be guarded on BEETLE_ENABLE_UI, which the bespoke-UI removal in 019305c
    // left defined by nothing, so the frontend fell through to the headless branch.
    //
    // The headless build has no launcher and nothing else will ask, so there it is still a hard stop.
#ifndef BEETLE_ENABLE_FRONTEND
    if (!have_rom) {
        message_box("No ROM configured. Pass the ROM path as the first argument "
                    "(this build has the in-game picker disabled).");
        return EXIT_FAILURE;
    }
#endif
    (void)have_rom;

    // Coordinator: the game thread blocks in wait_for_game_started() until start_game() runs. The VI
    // thread only seeds a dummy OSViMode while !is_game_started(); starting before its first tick
    // makes update_vi() deref a null mode — so we wait for g_bar_vi_ticked (renderer presented a
    // frame, which also means the launcher can draw over it). recomp::start() below blocks the main
    // thread, so this runs on a detached thread.
#ifndef BEETLE_ENABLE_FRONTEND
    // Auto-start, for builds WITHOUT the RecompFrontend launcher.
    //
    // Not used with the frontend, for two reasons. Correctness: recompui's
    // add_start_game_or_load_rom_option() calls recomp::start_game() itself once librecomp reports a
    // valid ROM (and runs the ROM picker when it does not), so the launcher owns that decision and
    // auto-starting would race it. And safety: the wait below is on g_bar_vi_ticked, which is set by
    // src/main/rt64_render_context.cpp -- the context the frontend REPLACES. Nothing would ever set
    // it, so this fell through the full 5s timeout and started the game before the VI thread had
    // ticked, which is exactly the null-mode deref the comment below warns about. That was a silent
    // crash roughly nine seconds after launch.
    std::thread([game_id]() {
        using namespace std::chrono_literals;
        for (int i = 0; i < 500 && !g_bar_vi_ticked.load(); i++) {
            std::this_thread::sleep_for(10ms);
        }

        // The ROM was already validated + cached in main(); start_game() loads it from the config dir.
        // Start the game right away — do NOT wait for "Play". The launcher/settings/cheats menu is an
        // OVERLAY drawn over the running game: RT64 only drives the UI's render+input render-hook while
        // the game is producing frames, so the menu cannot be interactive before the game starts. The
        // launcher stays shown over the (booting) game until the user clicks Play (which hides it);
        // F1 reopens the menu in-game. BAR_SKIP_LAUNCHER starts with the overlay hidden (headless).

        // Upstream added game modes: start_game now takes a mode id alongside the game id. BAR has
        // no alternate modes, so it starts in the default (empty) mode.
        recomp::start_game(game_id, "");
#ifdef BEETLE_ENABLE_UI
        bar_ui::on_game_started();   // mark game started (enables F1); the launcher stays as an overlay
#endif
    }).detach();
#endif // !BEETLE_ENABLE_FRONTEND

    // ---- Assemble callbacks (field names verified against the vendored headers) ----
    recomp::rsp::callbacks_t rsp_callbacks{};                  // MANDATORY
    rsp_callbacks.get_rsp_microcode = get_rsp_microcode;

    ultramodern::renderer::callbacks_t renderer_callbacks{};   // MANDATORY
#ifdef BEETLE_ENABLE_FRONTEND
    // recompui draws its menus over the game, so it supplies its own RT64 context; use that instead
    // of src/main/rt64_render_context.cpp. bar::frontend::create_render_context adapts the runtime's
    // 3-argument callback to recompui's 4-argument factory, and pins Console presentation so the
    // main-menu film-roll (a VI-origin pan that never redraws) still animates.
    renderer_callbacks.create_render_context = bar::frontend::create_render_context;
#else
    renderer_callbacks.create_render_context = bar_create_rt64_render_context;
#endif

    ultramodern::gfx_callbacks_t gfx_callbacks{};
    gfx_callbacks.create_gfx    = create_gfx;
    gfx_callbacks.create_window = create_window;
    gfx_callbacks.update_gfx    = update_gfx;

    ultramodern::audio_callbacks_t audio_callbacks{};
    audio_callbacks.queue_samples        = queue_samples;
    audio_callbacks.get_frames_remaining = get_frames_remaining;
    audio_callbacks.set_frequency        = set_frequency;

    ultramodern::input::callbacks_t input_callbacks{};
    input_callbacks.poll_input = input_poll;
    input_callbacks.get_input  = input_get;
    input_callbacks.set_rumble = input_set_rumble;
    input_callbacks.get_connected_device_info = input_get_device_info;

    ultramodern::error_handling::callbacks_t error_handling_callbacks{};
    error_handling_callbacks.message_box = message_box;

    ultramodern::threads::callbacks_t threads_callbacks{};
    threads_callbacks.get_game_thread_name = get_game_thread_name;

    recomp::Configuration config{};
    config.project_version          = project_version;
    config.rsp_callbacks            = rsp_callbacks;
    config.renderer_callbacks       = renderer_callbacks;
    config.audio_callbacks          = audio_callbacks;
    config.input_callbacks          = input_callbacks;
    config.gfx_callbacks            = gfx_callbacks;
    config.error_handling_callbacks = error_handling_callbacks;
    config.threads_callbacks        = threads_callbacks;
    // MENU-FPS FIX: BAR's SI (controller) event queue (main.c:311, D_8002F828) is only capacity 3, and our
    // low-level __osSiRawStartDma stub posts an SI completion per call. BAR doesn't drain them all during
    // the menu, so the queue fills with stale completions; with the default requeue_si=true, every new SI
    // completion then BOUNCES (re-queues) off the full queue in a ~15M/sec busy-spin that starves the
    // cooperative scheduler and throttled the menu to ~10fps. SI completions are disposable (live input is
    // re-read from PIF RAM each frame), so drop the excess instead of bouncing it.
    config.message_queue_control.requeue_si = (std::getenv("BAR_REQUEUE_SI") != nullptr);  // R6 bisect: default false (the menu-FPS fix); BAR_REQUEUE_SI=1 reverts to stock true
    // config.window_handle / events_callbacks: defaults are fine for now.

    // Cooperative audio-thread preemption: raise a host "yield now" flag at ~500Hz; a poll injected at every
    // recompiled-function prologue (fix-recompiled.sh rule F) then yields to the audio manager so long
    // straight-line game-thread compute can't starve audio (-> no underrun crackle at a low buffer). The flag
    // is gated to game threads once running, so starting the timer before the game spins up is harmless.
    extern void bar_start_preempt_timer();
    extern void bar_stop_preempt_timer();
    bar_start_preempt_timer();

#ifdef BEETLE_ENABLE_FRONTEND
    // Program identity, primary font and the launcher layout. Must precede recomp::start(), which
    // brings up the renderer — recompui builds its menus during that bring-up, and throws if no
    // primary font has been registered by then.
    bar::frontend::install();
#endif

    // Blocks until the game exits.
    recomp::start(config);
    bar_stop_preempt_timer();
    return EXIT_SUCCESS;
}
