// register_overlays.cpp — wire the N64Recomp-generated section/overlay tables into librecomp.
//
// N64Recomp emits RecompiledFuncs/recomp_overlays.inl (git-ignored, regenerated by
// `./N64Recomp beetle-adventure-racing-recomp.toml`). That file defines, as file-static data:
//   static SectionTableEntry section_table[];     // one entry per code section (base + ~130 module overlays)
//   const size_t num_sections;                    // TOTAL ELF sections incl. data (BAR: 413)
//   static int overlay_sections_by_index[];       // overlay index -> code-section position
//
// librecomp keys its reloc/section bookkeeping by *section index* (relocs target indices well
// past the code-section count), so total_num_sections must be `num_sections`, NOT
// ARRLEN(section_table). init_overlays() (called by the runtime on the game thread) allocates
// section_addresses[total_num_sections].
#include "recomp.h"
#include "librecomp/overlays.hpp"

#include "recomp_overlays.inl"   // defines section_table[], num_sections, overlay_sections_by_index[]

void bar_register_overlays() {
    recomp::overlays::overlay_section_table_data_t sections{};
    sections.code_sections      = section_table;
    sections.num_code_sections  = ARRLEN(section_table);
    sections.total_num_sections = num_sections;

    recomp::overlays::overlays_by_index_t overlays{};
    overlays.table = overlay_sections_by_index;
    overlays.len   = ARRLEN(overlay_sections_by_index);

    recomp::overlays::register_overlays(sections, overlays);
}
